// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwLtO-Wxl_56XoAM2d6ZJq0fJ0KTr-1X4',
    appId: '1:96327654736:web:5e021a031f45a4874d6055',
    messagingSenderId: '96327654736',
    projectId: 'foodinventory-8f2ad',
    authDomain: 'foodinventory-8f2ad.firebaseapp.com',
    storageBucket: 'foodinventory-8f2ad.firebasestorage.app',
    measurementId: 'G-YDC7ECDEH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCveB1cS6WouEECEa2R6xF3apcVp4Qry8o',
    appId: '1:96327654736:android:921167f2943e89ac4d6055',
    messagingSenderId: '96327654736',
    projectId: 'foodinventory-8f2ad',
    storageBucket: 'foodinventory-8f2ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-pOYwWOTMnbvVf1pZliORDWc4D0dsCF0',
    appId: '1:96327654736:ios:bb62a57d6c33f43d4d6055',
    messagingSenderId: '96327654736',
    projectId: 'foodinventory-8f2ad',
    storageBucket: 'foodinventory-8f2ad.firebasestorage.app',
    iosBundleId: 'com.example.foodInventoryTrackingApp',
  );
}